[2022-12-28 14:27:15 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-12-28 14:27:15 +0000] [9] [INFO] Listening at: http://0.0.0.0:8081 (9)
[2022-12-28 14:27:15 +0000] [9] [INFO] Using worker: gevent
[2022-12-28 14:27:15 +0000] [12] [INFO] Booting worker with pid: 12
[2022-12-28 14:27:15 +0000] [13] [INFO] Booting worker with pid: 13
[2022-12-28 14:28:02 +0000] [13] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/usr/api/api/resource/login_resource.py", line 56, in on_post
    self.login(req, resp)
  File "/usr/api/api/resource/login_resource.py", line 19, in login
    if not req_params or not req_params["Username"] or not req_params["Password"]:
KeyError: 'Username'
[2022-12-28 14:38:18 +0000] [9] [INFO] Handling signal: term
[2022-12-28 14:38:18 +0000] [13] [INFO] Worker exiting (pid: 13)
In req
In req
[2022-12-28 14:38:18 +0000] [12] [INFO] Worker exiting (pid: 12)
In req
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNocmlzdG9zeiIsInJvbGVzIjpbImFkbWluIl0sImV4cCI6MTY3NDkxNjA1OSwiaWF0IjoxNjcyMjM3NjU5fQ.oimsOTFpM9gdyOuYUf2U9KCFTYOIxiOdSoyfPJvumkU
[2022-12-28 14:38:19 +0000] [9] [INFO] Shutting down: Master
[2022-12-28 14:38:30 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2022-12-28 14:38:30 +0000] [8] [INFO] Listening at: http://0.0.0.0:8081 (8)
[2022-12-28 14:38:30 +0000] [8] [INFO] Using worker: gevent
[2022-12-28 14:38:30 +0000] [11] [INFO] Booting worker with pid: 11
[2022-12-28 14:38:30 +0000] [12] [INFO] Booting worker with pid: 12
[2022-12-28 14:39:13 +0000] [12] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/usr/api/api/resource/login_resource.py", line 57, in on_post
    self.login(req, resp)
  File "/usr/api/api/resource/login_resource.py", line 20, in login
    if not req_params or not req_params["Username"] or not req_params["Password"]:
KeyError: 'Username'
[2022-12-28 14:39:18 +0000] [8] [INFO] Handling signal: term
[2022-12-28 14:39:18 +0000] [11] [INFO] Worker exiting (pid: 11)
In req
{'Username': 'christosz', 'Password': '1234'}
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNocmlzdG9zeiIsInJvbGVzIjpbImFkbWluIl0sImV4cCI6MTY3NDkxNjcxMywiaWF0IjoxNjcyMjM4MzEzfQ.lDaXKzYwZjvHZ5ORnxSHteAeUkOo3Mq9pNZtfdZdIzE
[2022-12-28 14:39:19 +0000] [12] [INFO] Worker exiting (pid: 12)
In req
In req
{'username': 'f', 'password': 'f'}
[2022-12-28 14:39:19 +0000] [8] [INFO] Shutting down: Master
[2022-12-28 14:40:27 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-12-28 14:40:27 +0000] [9] [INFO] Listening at: http://0.0.0.0:8081 (9)
[2022-12-28 14:40:27 +0000] [9] [INFO] Using worker: gevent
[2022-12-28 14:40:27 +0000] [12] [INFO] Booting worker with pid: 12
[2022-12-28 14:40:27 +0000] [13] [INFO] Booting worker with pid: 13
[2022-12-28 14:40:57 +0000] [12] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 269, in get
    result = next(queryset)
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 1594, in __next__
    raw_doc = next(self._cursor)
  File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1251, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/usr/api/api/resource/login_resource.py", line 57, in on_post
    self.login(req, resp)
  File "/usr/api/api/resource/login_resource.py", line 26, in login
    self._authenticate(req_params["username"], req_params["password"], req, resp)
  File "/usr/api/api/resource/login_resource.py", line 34, in _authenticate
    users = self.user_service.get_user(username, password)
  File "/usr/api/api/services/user_service.py", line 37, in get_user
    user = User.objects.get(username=username)
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 272, in get
    raise queryset._document.DoesNotExist(msg)
api.model.user.DoesNotExist: User matching query does not exist.
[2022-12-28 15:51:30 +0000] [12] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/usr/api/api/resource/login_resource.py", line 57, in on_post
    self.login(req, resp)
  File "/usr/api/api/resource/login_resource.py", line 20, in login
    if not req_params or not req_params["username"] or not req_params["password"]:
KeyError: 'username'
[2022-12-28 15:52:32 +0000] [12] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 269, in get
    result = next(queryset)
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 1594, in __next__
    raw_doc = next(self._cursor)
  File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1251, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/usr/api/api/resource/login_resource.py", line 57, in on_post
    self.login(req, resp)
  File "/usr/api/api/resource/login_resource.py", line 26, in login
    self._authenticate(req_params["username"], req_params["password"], req, resp)
  File "/usr/api/api/resource/login_resource.py", line 34, in _authenticate
    users = self.user_service.get_user(username, password)
  File "/usr/api/api/services/user_service.py", line 37, in get_user
    user = User.objects.get(username=username)
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 272, in get
    raise queryset._document.DoesNotExist(msg)
api.model.user.DoesNotExist: User matching query does not exist.
[2022-12-28 15:54:18 +0000] [9] [INFO] Handling signal: term
[2022-12-28 15:54:19 +0000] [13] [INFO] Worker exiting (pid: 13)
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNocmlzdG9zeiIsInJvbGVzIjpbImFkbWluIl0sImV4cCI6MTY3NDkxNjg4NywiaWF0IjoxNjcyMjM4NDg3fQ.3gT8STs5DzMZcjO8eF1gVQal7Y8EcNSKhIuPy5MHKE8
[2022-12-28 15:54:19 +0000] [12] [INFO] Worker exiting (pid: 12)
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNocmlzdG9zeiIsInJvbGVzIjpbImFkbWluIl0sImV4cCI6MTY3NDkxNjg0MiwiaWF0IjoxNjcyMjM4NDQyfQ.SSC12UC_mReJSWHsaBnt3oa1fr7Xh5kaesQBhHiIaWg
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNocmlzdG9zeiIsInJvbGVzIjpbImFkbWluIl0sImV4cCI6MTY3NDkyMTE0OCwiaWF0IjoxNjcyMjQyNzQ4fQ.hbKUxlRTvD9V2aGfDSJ_Ojt7ObHRYLfHWGPJF56gn_M
[2022-12-28 15:54:19 +0000] [9] [INFO] Shutting down: Master
[2022-12-28 15:54:27 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2022-12-28 15:54:27 +0000] [8] [INFO] Listening at: http://0.0.0.0:8081 (8)
[2022-12-28 15:54:27 +0000] [8] [INFO] Using worker: gevent
[2022-12-28 15:54:27 +0000] [11] [INFO] Booting worker with pid: 11
[2022-12-28 15:54:27 +0000] [12] [INFO] Booting worker with pid: 12
[2022-12-28 15:56:52 +0000] [12] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/usr/api/api/resource/login_resource.py", line 57, in on_post
    self.login(req, resp)
  File "/usr/api/api/resource/login_resource.py", line 26, in login
    self._authenticate(req_params["username"], req_params["password"], req, resp)
  File "/usr/api/api/resource/login_resource.py", line 34, in _authenticate
    users = self.user_service.get_user(username, password)
  File "/usr/api/api/services/user_service.py", line 38, in get_user
    if User.validate_login(user.password, password):
AttributeError: 'QuerySet' object has no attribute 'password'
[2022-12-28 15:57:50 +0000] [12] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/usr/api/api/resource/login_resource.py", line 57, in on_post
    self.login(req, resp)
  File "/usr/api/api/resource/login_resource.py", line 26, in login
    self._authenticate(req_params["username"], req_params["password"], req, resp)
  File "/usr/api/api/resource/login_resource.py", line 34, in _authenticate
    users = self.user_service.get_user(username, password)
  File "/usr/api/api/services/user_service.py", line 38, in get_user
    if User.validate_login(user.password, password):
AttributeError: 'QuerySet' object has no attribute 'password'
[2022-12-28 15:57:58 +0000] [11] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/usr/api/api/resource/login_resource.py", line 57, in on_post
    self.login(req, resp)
  File "/usr/api/api/resource/login_resource.py", line 26, in login
    self._authenticate(req_params["username"], req_params["password"], req, resp)
  File "/usr/api/api/resource/login_resource.py", line 34, in _authenticate
    users = self.user_service.get_user(username, password)
  File "/usr/api/api/services/user_service.py", line 38, in get_user
    if User.validate_login(user.password, password):
AttributeError: 'QuerySet' object has no attribute 'password'
[2022-12-28 15:58:25 +0000] [8] [INFO] Handling signal: term
[2022-12-28 15:58:26 +0000] [11] [INFO] Worker exiting (pid: 11)
[2022-12-28 15:58:26 +0000] [12] [INFO] Worker exiting (pid: 12)
[2022-12-28 15:58:26 +0000] [8] [INFO] Shutting down: Master
[2022-12-28 15:59:04 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-12-28 15:59:04 +0000] [9] [INFO] Listening at: http://0.0.0.0:8081 (9)
[2022-12-28 15:59:04 +0000] [9] [INFO] Using worker: gevent
[2022-12-28 15:59:04 +0000] [12] [INFO] Booting worker with pid: 12
[2022-12-28 15:59:04 +0000] [13] [INFO] Booting worker with pid: 13
[2022-12-28 16:08:02 +0000] [12] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 269, in get
    result = next(queryset)
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 1594, in __next__
    raw_doc = next(self._cursor)
  File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1251, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
  File "falcon/api.py", line 269, in falcon.api.API.__call__
  File "/usr/api/api/resource/login_resource.py", line 57, in on_post
    self.login(req, resp)
  File "/usr/api/api/resource/login_resource.py", line 26, in login
    self._authenticate(req_params["username"], req_params["password"], req, resp)
  File "/usr/api/api/resource/login_resource.py", line 34, in _authenticate
    users = self.user_service.get_user(username, password)
  File "/usr/api/api/services/user_service.py", line 37, in get_user
    user = User.objects.get(username=username)
  File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 272, in get
    raise queryset._document.DoesNotExist(msg)
api.model.user.DoesNotExist: User matching query does not exist.
[2022-12-28 16:10:56 +0000] [9] [INFO] Handling signal: term
[2022-12-28 16:10:56 +0000] [13] [INFO] Worker exiting (pid: 13)
[2022-12-28 16:10:57 +0000] [12] [INFO] Worker exiting (pid: 12)
[2022-12-28 16:10:57 +0000] [9] [INFO] Shutting down: Master
[2022-12-28 16:11:08 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-12-28 16:11:08 +0000] [9] [INFO] Listening at: http://0.0.0.0:8081 (9)
[2022-12-28 16:11:08 +0000] [9] [INFO] Using worker: gevent
[2022-12-28 16:11:08 +0000] [12] [INFO] Booting worker with pid: 12
[2022-12-28 16:11:08 +0000] [13] [INFO] Booting worker with pid: 13
[2022-12-28 17:04:59 +0000] [9] [INFO] Handling signal: term
[2022-12-28 17:05:00 +0000] [12] [INFO] Worker exiting (pid: 12)
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNocmlzdG9zeiIsInJvbGVzIjpbImFkbWluIl0sImV4cCI6MTY3NDkyNTQwMCwiaWF0IjoxNjcyMjQ3MDAwfQ.vwJMmm7oPjiMKsqox9NhrGQnIF9H-s-ekPNj7LR3TjA
[2022-12-28 17:05:00 +0000] [13] [INFO] Worker exiting (pid: 13)
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNocmlzdG9zeiIsInJvbGVzIjpbImFkbWluIl0sImV4cCI6MTY3NDkyMjg0OCwiaWF0IjoxNjcyMjQ0NDQ4fQ.pjQ1dJ0dur6gNGT_f3zPOMc7RxhFrbsVLQBx6XTB-Ck
[2022-12-28 17:05:01 +0000] [9] [INFO] Shutting down: Master
[2022-12-28 17:05:32 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-12-28 17:05:32 +0000] [9] [INFO] Listening at: http://0.0.0.0:8081 (9)
[2022-12-28 17:05:32 +0000] [9] [INFO] Using worker: gevent
[2022-12-28 17:05:32 +0000] [12] [INFO] Booting worker with pid: 12
[2022-12-28 17:05:32 +0000] [13] [INFO] Booting worker with pid: 13
[2022-12-28 18:23:38 +0000] [9] [INFO] Handling signal: term
[2022-12-28 18:23:38 +0000] [12] [INFO] Worker exiting (pid: 12)
[2022-12-28 18:23:38 +0000] [13] [INFO] Worker exiting (pid: 13)
[2022-12-28 18:23:38 +0000] [9] [INFO] Shutting down: Master
[2022-12-28 21:27:01 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-12-28 21:27:01 +0000] [9] [INFO] Listening at: http://0.0.0.0:8081 (9)
[2022-12-28 21:27:01 +0000] [9] [INFO] Using worker: gevent
[2022-12-28 21:27:01 +0000] [12] [INFO] Booting worker with pid: 12
[2022-12-28 21:27:01 +0000] [13] [INFO] Booting worker with pid: 13
[2022-12-28 21:34:37 +0000] [9] [INFO] Handling signal: term
[2022-12-28 21:34:38 +0000] [12] [INFO] Worker exiting (pid: 12)
[2022-12-28 21:34:38 +0000] [13] [INFO] Worker exiting (pid: 13)
[2022-12-28 21:34:39 +0000] [9] [INFO] Shutting down: Master
